-- Tabla principal de historial
CREATE TABLE IF NOT EXISTS roulette_history (
    id SERIAL PRIMARY KEY,
    numbers_string TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW())
);

-- Tabla para números individuales
CREATE TABLE IF NOT EXISTS roulette_numbers_individual (
    id SERIAL PRIMARY KEY,
    history_entry_id INTEGER NOT NULL REFERENCES roulette_history(id) ON DELETE CASCADE,
    number_value INTEGER NOT NULL CHECK (number_value >= 0 AND number_value <= 36),
    color TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()),
    CONSTRAINT unique_number_per_history UNIQUE (history_entry_id, number_value)
);

-- Índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_roulette_history_created_at ON roulette_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_roulette_numbers_history_id ON roulette_numbers_individual(history_entry_id);
CREATE INDEX IF NOT EXISTS idx_roulette_numbers_value ON roulette_numbers_individual(number_value);

-- Tabla para el estado del analizador
CREATE TABLE IF NOT EXISTS analyzer_state (
    id INTEGER PRIMARY KEY DEFAULT 1,
    aciertos_individual INTEGER DEFAULT 0,
    aciertos_grupo INTEGER DEFAULT 0,
    aciertos_vecinos_0_10 INTEGER DEFAULT 0,
    aciertos_vecinos_7_27 INTEGER DEFAULT 0,
    total_predicciones_evaluadas INTEGER DEFAULT 0,
    aciertos_tia_lu INTEGER DEFAULT 0,
    tia_lu_estado_activa BOOLEAN DEFAULT FALSE,
    tia_lu_estado_giros_jugados INTEGER DEFAULT 0,
    tia_lu_estado_activada_con_33 BOOLEAN DEFAULT FALSE,
    tia_lu_estado_contador_desencadenantes_consecutivos INTEGER DEFAULT 0,
    tia_lu_estado_ultimo_numero_fue_desencadenante BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW())
);

-- Tabla para definiciones de sectores
CREATE TABLE IF NOT EXISTS sectores_definiciones (
    id SERIAL PRIMARY KEY,
    nombre_sector TEXT NOT NULL UNIQUE,
    numeros TEXT NOT NULL, -- Almacenado como string separado por comas
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW())
);

-- Tabla para conteos de sectores
CREATE TABLE IF NOT EXISTS sectores_conteos (
    id SERIAL PRIMARY KEY,
    id_estado_analizador INTEGER NOT NULL DEFAULT 1 REFERENCES analyzer_state(id),
    id_sector_definicion INTEGER NOT NULL REFERENCES sectores_definiciones(id) ON DELETE CASCADE,
    conteo INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()),
    CONSTRAINT unique_sector_conteo UNIQUE (id_estado_analizador, id_sector_definicion)
);

-- Tabla para almacenar predicciones anteriores
CREATE TABLE IF NOT EXISTS predicciones_anteriores (
    id SERIAL PRIMARY KEY,
    grupo_20 INTEGER[] NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW())
);

-- Índice para optimizar la búsqueda de la última predicción
CREATE INDEX IF NOT EXISTS idx_predicciones_created_at ON predicciones_anteriores(created_at DESC);

-- Comentarios de las tablas
COMMENT ON TABLE roulette_history IS 'Almacena el historial completo de números de la ruleta como cadenas';
COMMENT ON TABLE roulette_numbers_individual IS 'Almacena cada número individualmente para análisis detallado';
COMMENT ON TABLE analyzer_state IS 'Almacena el estado global del analizador de ruleta';
COMMENT ON TABLE sectores_definiciones IS 'Define los sectores personalizados de la ruleta';
COMMENT ON TABLE sectores_conteos IS 'Almacena los conteos de aciertos por sector';

-- Tabla para almacenar el historial de números
CREATE TABLE IF NOT EXISTS historial_numeros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER NOT NULL CHECK (numero >= 0 AND numero <= 36),
    color VARCHAR(10) NOT NULL CHECK (color IN ('Rojo', 'Negro', 'Verde')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()) NOT NULL,
    session_id UUID NOT NULL
);

-- Tabla para almacenar las predicciones
CREATE TABLE IF NOT EXISTS predicciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_20 INTEGER[] NOT NULL,
    color_predicho VARCHAR(10) NOT NULL CHECK (color_predicho IN ('Rojo', 'Negro')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()) NOT NULL,
    session_id UUID NOT NULL
);

-- Tabla para almacenar los resultados de las apuestas
CREATE TABLE IF NOT EXISTS resultados_apuestas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_jugado INTEGER NOT NULL CHECK (numero_jugado >= 0 AND numero_jugado <= 36),
    color_jugado VARCHAR(10) NOT NULL CHECK (color_jugado IN ('Rojo', 'Negro', 'Verde')),
    prediccion_id BIGINT REFERENCES predicciones(id),
    acierto_numero BOOLEAN NOT NULL,
    acierto_color BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()) NOT NULL,
    session_id UUID NOT NULL
);

-- Índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_historial_numeros_session ON historial_numeros(session_id);
CREATE INDEX IF NOT EXISTS idx_predicciones_session ON predicciones(session_id);
CREATE INDEX IF NOT EXISTS idx_resultados_session ON resultados_apuestas(session_id);
CREATE INDEX IF NOT EXISTS idx_historial_created_at ON historial_numeros(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_predicciones_created_at ON predicciones(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sectores_nombre ON sectores_definiciones(nombre_sector);
CREATE INDEX IF NOT EXISTS idx_sectores_conteos_estado ON sectores_conteos(id_estado_analizador);

-- Comentarios de las tablas
COMMENT ON TABLE historial_numeros IS 'Almacena el historial de números jugados y sus colores';
COMMENT ON TABLE predicciones IS 'Almacena las predicciones de grupos de números y colores';
COMMENT ON TABLE resultados_apuestas IS 'Almacena los resultados de las apuestas y sus aciertos';
COMMENT ON TABLE analyzer_state IS 'Almacena el estado global del analizador de ruleta';
COMMENT ON TABLE sectores_definiciones IS 'Define los sectores personalizados de la ruleta';
COMMENT ON TABLE sectores_conteos IS 'Almacena los conteos de aciertos por sector'; 